AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFront distribution for MLOps Platform frontend'

Parameters:
  Environment:
    Type: String
    Default: dev

  FrontendBucketName:
    Type: String
    Default: ''
    Description: (Optional) S3 bucket name for frontend assets. If empty, `FrontendBucketArn` must be provided.

  FrontendBucketArn:
    Type: String
    Default: ''
    Description: (Optional) ARN of the S3 bucket (e.g. arn:aws:s3:::bucket-name). If provided, bucket name will be derived from this ARN.

Conditions:
  UseBucketArn: !Not [ !Equals [ !Ref FrontendBucketArn, '' ] ]

Resources:
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'mlops-${Environment}-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName:
              Fn::If:
                - UseBucketArn
                - Fn::Join:
                    - ''
                    - - Fn::Select:
                        - 5
                        - Fn::Split:
                            - ':'
                            - !Ref FrontendBucketArn
                      - !Sub ".s3.${AWS::Region}.amazonaws.com"
                - !Sub '${FrontendBucketName}.s3.${AWS::Region}.amazonaws.com'
            OriginAccessControlId: !GetAtt OriginAccessControl.Id
            S3OriginConfig: {}
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TrustedSigners: []
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !If
        - UseBucketArn
        - Fn::Select:
            - 5
            - Fn::Split:
                - ':'
                - !Ref FrontendBucketArn
        - !Ref FrontendBucketName
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource:
              Fn::If:
                - UseBucketArn
                - Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - Fn::Select:
                          - 5
                          - Fn::Split:
                              - ':'
                              - !Ref FrontendBucketArn
                      - '/*'
                - !Sub 'arn:aws:s3:::${FrontendBucketName}/*'
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

Outputs:
  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution

  CloudFrontURL:
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
